# Generated by Django 4.1.6 on 2023-02-13 17:07

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="blog_post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("sub_title", models.CharField(max_length=500)),
                ("blog_image", models.ImageField(upload_to="blog_img")),
                ("body_content", tinymce.models.HTMLField()),
                ("publish_date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
